### ISSUE TITLE
Playlist-associated transpositions are not supported ?

### ISSUE THREAD

**Issue by strk** [sciurius/perl-Data-iRealPro#4]
When converting a playlist to PDF (didn't check other output formats) all scores are printed in original key, completely ignoring transposition associated with the piece as added to the playlist.

I dont' know the details of the format but I'm sure there must be a transposition encoded for each piece as iRealPro is able to import that playlist retaining the key set for each piece instead.

**Comment by sciurius** [comment]
This is planned for the next release. Stay tuned.

**Comment by sciurius** [comment]
Version 1.11 should display the songs in the transposed keys, just like the iRealPro player.
Also, the --transpose command line options should now work for all backends.

**Comment by strk** [comment]
For the record, it was fixed in
c550e7a12f8b0e11cfc973b1c75ea738c64aa396
