### ISSUE TITLE
Transpositions broken ?

### ISSUE THREAD

**Issue by strk** [sciurius/perl-Data-iRealPro#7]
Is transposition still missing from non-playlist support ?
Try this: http://strk.kbt.io/tmp/SittingOnTheDockOfTheBay.html
Should come up with G as the first chord ...

See #4 for a recent fix in this spot

**Comment by sciurius** [comment]
Yikes... I made the assumption that no actual key was the same as key C. That was wrong.
The current git version has a fix.

**Comment by strk** [comment]
With current master (4aca107bb93) I get:
Undefined subroutine &App::Packager::GetResourcePath called at /home/strk/perl5/lib/perl5/Data/iRealPro/Output/Imager.pm line 38.

**Comment by strk** [comment]
After fixing the GetResourcePath issue I still have problems with transposition .
See this playlist: http://strk.kbt.io/tmp/Elif.html
NightAndDay (song 10) should come out with first chord being Emaj7, comes out as Abmaj7 instead
This happens as of 99f696ff329af705e20ac04745375b7d82959fff

**Comment by sciurius** [comment]
When I load the playlist in iRealPro, all songs show exactly as irealcvt prints them. Night and Day starts with Abmaj7.
![image](https://user-images.githubusercontent.com/1118804/48304657-0eca1a00-e515-11e8-9253-a2b2d4775040.png)

**Comment by strk** [comment]
Ah, sorry. I had the wrong file. I've now overridden it and it works great.
