### ISSUE TITLE
Undefined subroutine &App::Packager::GetResourcePath called at /home/strk/perl5/lib/perl5/Data/iRealPro/Output/Imager.pm line 38.

### ISSUE THREAD

**Issue by strk** [sciurius/perl-Data-iRealPro#8]
As of 470906404c9b0faeec971b86793e9b118af6186d I cannot use irealcvt as I always get this error:
> Undefined subroutine &App::Packager::GetResourcePath called at /home/strk/perl5/lib/perl5/Data/iRealPro/Output/Imager.pm line 38.

**Comment by sciurius** [comment]
Do you have App::Packager version 1.430 installed?

**Comment by strk** [comment]
On a different machine, that cleanup did not work.
Instead I got a warning:

Warning: prerequisite App::Packager 1.42 not found.

This is as of 99f696ff329af705e20ac04745375b7d82959fff, which 
supposedly switched to require 1.430, so I dunno where that
1.42 comes from...

**Comment by sciurius** [comment]
Good to see you have this sorted out!
I've added a requirement for 1.43 in the program, so it won't run unless 1.43 (or newer) is installed.
I didn't update the Makefile.PL yet, that still requires only 1.42. This should be fixed in git now.
Thanks for your patience.
